name: Create Release on Push to Main

on:
  push:
    branches:
      - main

permissions:
  contents: write
  issues: write
  discussions: write
  pull-requests: write
  actions: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up GitHub CLI
        uses: cli/cli@v3

      - name: Authenticate GitHub CLI
        run: gh auth login --with-token < ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Git
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Create Release
        id: create_release
        run: |
          VERSION=$(date +'%Y%m%d%H%M%S')  # You can use a different versioning strategy
          gh release create "v${VERSION}" --title "Release v${VERSION}" --notes "Release created from push to main"  # You can customize the message or notes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
